### ISSUE TITLE
[ETC] 피그마에 로그인 화면 스케치 작업

### ISSUE THREAD

**Issue by Parksunyoung1** [ummiih/opensw-yuyeonga#22]
## ✅ TODO 및 진행현황 

- [x] 들어갈 기능 정하기
- [x] 사진 선택하는 페이지 
- [x] 이름과 닉네임 선택하는 페이지
- [x] 로그인 마치고 시작하는 화면 페이지
