### ISSUE TITLE
[FEATURE] 첫 로그인 화면 기능 퍼블리싱

### ISSUE THREAD

**Issue by ayuuuneee** [ummiih/opensw-yuyeonga#25]
## 🌴 작업 브랜치 
feature/initial-login-screen-pub
## 💼 TASK 개요 
![image](https://github.com/ummiih/opensw-yuyeonga/assets/147591107/a3a354a9-ea37-4de6-ab56-2a88681272da)

## ✅ TODO 및 진행현황 

- [ ] 로고 상단에 띄우기
- [ ] 아이디 입력 받기
- [ ] 비밀번호 입력 받기
